web3 and function calls
n1c01a5/recover-website pull request #31
Opened 2020-12-16 10:58 UTC by chaitanya5

- Integrated With Metamask and Web3
- Calls contract functions to buy loser-box.

The loser-box can be now bought with any token with any amount (this has been done for testing purposes only)
If you want to change that, just change the below lines as described below

### Before at  ./pages/loser-box.js
**Line 136** 
` const erc20ContractAddress = '0x75A27fa3F7ec1ECB1fd05618DB5Fab78de0755D2';`
**Line 141**
` const tokenAmount = 10;`

### After at ./pages/loser-box.js
**Line 136** 
` const erc20ContractAddress = 'YOUR ERC20 TOKEN ADDRESS';`
**Line 141**
` const tokenAmount = YOUR REQUIRED AMOUNT;`

2021-01-03 10:43 UTC, n1c01a5 commented
@chaitanya5 can you respect the "snake case" format to name the files.

2021-01-03 11:05 UTC, n1c01a5 commented
@chaitanya5 there is an issue with the alignement of the "Recipient's name" field.

2021-01-03 11:06 UTC, n1c01a5 commented
@chaitanya5 the second step has to be "optional" as well.

2021-01-07 17:38 UTC, n1c01a5 commented
As discussed, the `connect Web3` will be not optional.

2021-01-07 17:39 UTC, n1c01a5 commented
@chaitanya5 there is too much space between the title and the content.

2021-01-07 17:40 UTC, n1c01a5 commented
@chaitanya5 don't put `*` and `(Optional)`. `(optional)` in lower case is enough.

2021-01-07 17:41 UTC, n1c01a5 commented
@chaitanya5 can put th elabel under the dot like https://codesandbox.io/s/3v8gs .

2021-01-07 17:51 UTC, n1c01a5 commented
@chaitanya5 also the header is not the same than the other page. You have to re-use the header to be consistant.

2021-01-07 18:43 UTC, chaitanya5 commented
@n1c01a5 , thank you for updating here. I was following whatever was shown in the Figma. I will make sure to implement it. 
Also please check the form validations thoroughly and let me know the changes. It's been a while changing the form and error validations from time to time. 
For convinience, let me summarise everthing,

1. can you respect the "kebab case" format to name the files.
2. there is too much space between the title and the content.
3. don't put * and (Optional). (optional) in lower case is enough.
4. can put th elabel under the dot like https://codesandbox.io/s/3v8gs .
5. also the header is not the same than the other page. You have to re-use the header to be consistant.

2021-01-08 00:12 UTC, bhavesh92pandey commented
@chaitanya5 Yes, there was (*) present in Figma design which I have removed now.

2021-01-14 10:51 UTC, bhavesh92pandey commented
In progress #65

2021-01-15 12:51 UTC, n1c01a5 requested changes

2021-01-16 11:41 UTC, n1c01a5 commented
@chaitanya5 can you fix the conflicts

2021-01-16 12:05 UTC, n1c01a5 requested changes

2021-01-16 12:05 UTC, n1c01a5 commented on pages/loserbox-stepper.js
> +  const handleNext = (networkId) => {
It's more something like `handleNextStep` to make explicit it's connected with the stepper.

2021-01-16 12:05 UTC, n1c01a5 commented on pages/loserbox-stepper.js
> +    console.log('activeStepNext', activeStep + 1)
Remove this log.

2021-01-16 12:05 UTC, n1c01a5 commented on pages/loserbox-stepper.js
> +let pageCount
It looks weird to have this.
Is it not possible to solve the state stepper with the `activeStap useState`?

2021-01-16 12:05 UTC, n1c01a5 commented on pages/pay-loserbox.js
> +        console.log('TxId', TxId)
Cna you remove all logs like this.

2021-01-19 18:40 UTC, n1c01a5 commented
@chaitanya5 fix the conflicts!

2021-01-20 09:46 UTC, bhavesh92pandey requested changes

2021-01-20 09:46 UTC, bhavesh92pandey commented on components/stepper/approve-dai.js
> +      to: envData.ERCTOKEN, // Required except during contract publications.
ERC_TOKEN

2021-01-20 09:46 UTC, bhavesh92pandey commented on components/stepper/approve-dai.js
> +        setTxerror(true)
setTXError

2021-01-20 09:46 UTC, bhavesh92pandey commented on components/stepper/connect-web3.js
> +  isnetworkWarning,
isNetworkWarning

2021-01-20 09:46 UTC, bhavesh92pandey commented on components/stepper/connect-web3.js
> +          {isnetworkWarning
isNetworkWarning

2021-01-20 09:46 UTC, bhavesh92pandey commented on components/stepper/transfer-dai.js
> +    if (isagree) {
isAgree

2021-01-20 09:46 UTC, bhavesh92pandey commented on components/stepper/transfer-dai.js
> +      {open && (
isOpen

2021-01-20 15:23 UTC, n1c01a5 commented
@chaitanya5 yes good think to use the `dex sdk`.

2021-01-20 17:50 UTC, bhavesh92pandey commented
Please resolve these conflicts as discussed

2021-01-20 18:49 UTC, merged