Abstract css code
n1c01a5/recover-website pull request #58
Opened 2021-01-11 21:56 UTC by amitg01

2021-01-11 21:58 UTC, amitg01 commented
@n1c01a5 Please merge PR #44, so that I can rebase this branch with master and resolve the merge conflicts.

2021-01-26 01:04 UTC, amitg01 commented
Hi @n1c01a5 @bhavesh92pandey The changes for layout and other minor fixes are done. Here is a demo: https://www.loom.com/share/b4cde9b7c0a54b399be672ec08b3812e

2021-01-26 08:26 UTC, bhavesh92pandey commented
Hi Amit, i saw the video but i think there are few changes still needs to be done. This we can discuss on the scheduled call

2021-01-26 09:05 UTC, amitg01 commented
Sure.

On Tue, Jan 26, 2021, 1:56 PM Bhavesh <notifications@github.com> wrote:

> Hi Amit, i saw the video but i think there are few changes still needs to
> be done. This we can discuss on the scheduled call
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/n1c01a5/recover-website/pull/58#issuecomment-767383614>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALX46B6YZBU3PS63SW4BCTDS3Z4D3ANCNFSM4V6HQ54Q>
> .
>

2021-01-28 11:01 UTC, n1c01a5 requested changes
I left my review. See my comments.

2021-01-28 11:01 UTC, n1c01a5 commented on styles/globals.scss
> +  line-height: 24px !important;
I am not big fan of these `!important` but ok.

2021-01-28 11:44 UTC, merged